language: python
python:
    - "2.7"
before_install:
    - wget http://naif.jpl.nasa.gov/pub/naif/generic_kernels/spk/planets/de432s.bsp
    - cp de432s.bsp ./EXOSIMS/Observatory/
    - mv de432s.bsp ./tests/TestSupport/
script:
    python -m unittest discover -v
