dist: xenial
language: python
python:
    - "2.7"
    - "3.6"
    - "3.7"
install:
    - pip install -r --upgrade requirements.txt
    - pip install -e .
script:
    coverage run -m unittest discover -v
after_success:
    coveralls

