version: 2.1
jobs:
  test:
    parallelism: 4
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.9.5"
    steps:
      - checkout
      - run: 
          name: Grant local/bin permission
          command: sudo chown -R circleci:circleci /usr/local/bin
      - run: 
          name: Grant lib/python3.9 permission
          command: sudo chown -R circleci:circleci /usr/local/lib/python3.9/site-packages
      - restore_cache:
          name: install dependencies start (install cache if one exists)
          key: -v3-{{ checksum "requirements.txt" }}
      - run: pip install --upgrade pip
      - run: pip install --upgrade -r requirements.txt
      - run: pip install coverage
      - run: pip install unittest-xml-reporting
      - run: pip install -e .
      - save_cache: 
          key: -v3-{{ checksum "requirements.txt" }}
          name: install dependencies end (generate cache if one doesn't exist)
          paths: 
            - ".venv"
            - "/usr/local/lib/python3.9/site-packages"
            - "/usr/local/bin"
      - run: mkdir -p coverages
      - run: 
          name: find and run tests and generate coverage files
          no_output_timeout: 60m
          command: |
            TESTFILES=$(circleci tests glob "tests/**/test_*.py" | circleci tests split --split-by=timings)
            python runtests.py $TESTFILES
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports 
      - persist_to_workspace:
          root: coverages
          paths: 
            - ./*

  done:
    docker:
    - image: "circleci/python:3.9.5"
    steps:
      - checkout
      - run: pip install coverage
      - run: pip install coveralls
      - attach_workspace: 
          at: ./ 
      - run: coverage combine
      - run: coveralls 

workflows:
  test_then_upload:
    jobs:
      - test
      - done: 
          requires: [test]
