version: 2.1

jobs:
  test:
    parallelism: 4
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.9.5"
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.9/site-packages
      - restore_cache: 
         key: -v3-{{ checksum "requirements.txt" }}
      - run: pip install --upgrade pip
      - run: pip install --upgrade -r requirements.txt
      - run: pip install -e .
      - save_cache: 
          key: -v3-{{ checksum "requirements.txt" }}
          paths: 
            - ".venv"
            - "/usr/local/lib/python3.9/site-packages"
            - "/usr/local/bin"
      - restore_cache: 
          key: -v1-{{ checksum "/home/circleci/circleci-python/EXOSIMS/Prototypes/Completeness.py" }}
      - run: TESTFILES=$(circleci tests glob "tests/**/test_*.py")
      - run: coverage run --parallel-mode -m unittest ${TESTFILES}
      - save_cache: 
          key: -v1-{{ checksum "/home/circleci/circleci-python/EXOSIMS/Prototypes/Completeness.py" }}
          paths: 
            - "/home/circleci/.EXOSIMS/cache/PlanetPopulationPlanetPhysicalModelBrownCompleteness100000000lambert14d3efb8ef02a7272a8adfcb89e73a2d.comp"
            - "/home/circleci/.EXOSIMS/cache/PlanetPopulationPlanetPhysicalModelGarrettCompleteness100000000lambert14d3efb8ef02a7272a8adfcb89e73a2dd871f10e74647ff3d45a505502f6d593.acomp"
            - "/home/circleci/.EXOSIMS/cache/PlanetPopulationPlanetPhysicalModelBrownCompleteness100000000lambertb0fbd473af51549eac25b282cff629c6.comp"
            - "/home/circleci/.EXOSIMS/cache/PlanetPopulationPlanetPhysicalModelGarrettCompleteness100000000lambertb0fbd473af51549eac25b282cff629c6abe35e7b88382448f746474db37f2694.acomp"
            - "/home/circleci/.EXOSIMS/cache/PlanetPopulationPlanetPhysicalModelGarrettCompleteness100000000lambertb0fbd473af51549eac25b282cff629c6abe35e7b88382448f746474db37f26948d6fc835a5dc95be7bc514c2ba363b2a.acomp"
      - run: coverage combine
      - run: coveralls

workflows:
  build_and_test:
    jobs:
      - test