version: 2.1

jobs:
  build:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: pip install --upgrade pip
      - run: pip install --upgrade -r requirements.txt
      - run: pip install -e .
  test:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: coverage run -m unittest discover -v

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build