version: 2.1

jobs:
  build:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.9.5"
    steps:
      - checkout
      - restore_cache: 
         key: -v2-{{ checksum "requirements.txt" }}
      - run: pip install --upgrade pip
      - run: pip install --upgrade -r requirements.txt
      - run: pip install -e .
      - save_cache: 
          key: -v2-{{ checksum "requirements.txt" }}
          paths: 
            - "/usr/local/lib/python3.9/site-packages"
  test:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.9.5"
    steps:
      - checkout
      - run: pip install --upgrade pip
      - run: pip install --upgrade -r requirements.txt
      - run: pip install -e .
      - restore_cache: 
         key: -v1-{{ checksum "exosims/prototypes/completeness.py" }}
      - run: coverage run -m unittest discover -v
      - save_cache: 
        key: -v1-{{ checksum "exosims/prototypes/completeness.py" }}
        paths: 
          - "/home/circleci/.EXOSIMS/cache/PlanetPopulationPlanetPhysicalModelBrownCompleteness100000000lambert14d3efb8ef02a7272a8adfcb89e73a2d.comp"
          - "/home/circleci/.EXOSIMS/cache/PlanetPopulationPlanetPhysicalModelGarrettCompleteness100000000lambert14d3efb8ef02a7272a8adfcb89e73a2dd871f10e74647ff3d45a505502f6d593.acomp"
          - "/home/circleci/.EXOSIMS/cache/PlanetPopulationPlanetPhysicalModelBrownCompleteness100000000lambertb0fbd473af51549eac25b282cff629c6.comp"
          - "/home/circleci/.EXOSIMS/cache/PlanetPopulationPlanetPhysicalModelGarrettCompleteness100000000lambertb0fbd473af51549eac25b282cff629c6abe35e7b88382448f746474db37f2694.acomp"
          - "/home/circleci/.EXOSIMS/cache/PlanetPopulationPlanetPhysicalModelGarrettCompleteness100000000lambertb0fbd473af51549eac25b282cff629c6abe35e7b88382448f746474db37f26948d6fc835a5dc95be7bc514c2ba363b2a.acomp"
      - run: coveralls

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build